In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv(r"../DataSets/diabetes.csv")

In [4]:
cols = list(df.columns)
print(cols)

['pr', 'glucose', 'bp_diastolic', 'skin_triceps', 'insulin', 'bmi', 'pedigree', 'age', 'label']

In [5]:
lbl = "label"

In [6]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion = "entropy", max_depth=3)

In [7]:
df.head()

,pr,glucose,bp_diastolic,skin_triceps,insulin,bmi,pedigree,age,label
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
cols.remove(lbl)
feature_cols = np.array(cols)
print(feature_cols)

['pr' 'glucose' 'bp_diastolic' 'skin_triceps' 'insulin' 'bmi' 'pedigree'
 'age']

In [9]:
X = df[feature_cols]
y = df[lbl]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [10]:
model = clf.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [11]:
from sklearn import metrics

result = metrics.confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)

In [12]:
result = metrics.confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[124  22]
 [ 31  54]]

In [13]:
TP = result[1, 1]
TN = result[0, 0]
FP = result[0, 1]
FN = result[1, 0]

In [14]:
print(TP)

54

In [15]:
print("Accuracy:\t",metrics.accuracy_score(y_test, y_pred))
print("Sensitivity:\t",metrics.recall_score(y_test, y_pred))
print("Specificity:\t",TN / (TN + FP))
print("Precision:\t",metrics.precision_score(y_test, y_pred))
print("Classification Eerror:", 1 - metrics.accuracy_score(y_test, y_pred))
print("False_Positive_Rate:",1 - TN / (TN + FP))

Accuracy:	 0.7705627705627706
Sensitivity:	 0.6352941176470588
Specificity:	 0.8493150684931506
Precision:	 0.7105263157894737
Classification Eerror: 0.22943722943722944
False_Positive_Rate: 0.15068493150684936

## Regression Accuracy

In [16]:
y = pd.DataFrame({"Orignal": y_test, "Predicted": y_pred})
y.head()

     Orignal  Predicted
285        0          0
101        0          0
581        0          0
352        0          0
726        0          0

In [ ]:
from sklearn.tree import export_graphviz
from six import StringIO  
from IPython.display import Image

In [ ]:
# import pydotplus